### PR TITLE
Fix return value for negative zero

### LINKED ISSUE #1: Returns negative 0
When given negative zero (`-0`), this module returns `-0` instead of `0`.

```js
console.log(require('stay-positive')(-0))
```

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #1

### CODE REVIEW

**Comment by contolini** [comment]
Thanks @LinusU! Can you add a new [test](https://github.com/cfpb/stay-positive/blob/master/test/stay-positive-tests.js) for this real quick?

**Comment by LinusU** [comment]
Done 👌

**Comment by LinusU** [comment]
Strange error on Travis:

> npm ERR! version not found: esprima-six@0.0.3

**Comment by contolini** [comment]
Hmmm probably some old dev deps are causing problems. I'll debug and publish in a bit. Thanks for the fix!

**Comment by contolini** [comment]
Published as 1.0.0.

**Comment by LinusU** [comment]
Thank you

**Pull request merged**
